[package]
name = "dundefsave"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compress = { version = "0.2.1", default-features = false, features = ["zlib"] }
deku = "0.16.0"
